/**
 * SMART ABSENSI GURU - GLOBAL CONSTANTS
 */

export const CONSTANTS = {
  ROLES: {
    GURU: 'GURU',
    KEPSEK: 'KEPSEK',
    ADMIN: 'ADMIN',
    OPERATOR: 'ADMIN',
  },

  ATTENDANCE_STATUS: {
    HADIR: 'HADIR',
    TERLAMBAT: 'TERLAMBAT',
    BELUM_ABSEN: 'BELUM_ABSEN',
    IZIN: 'IZIN',
    SAKIT: 'SAKIT',
    DINAS: 'DINAS',
    ALFA: 'ALFA',
  },

  LEAVE_TYPES: {
    SAKIT: 'SAKIT',
    IZIN: 'IZIN',
    DINAS_LUAR: 'DINAS_LUAR',
    KOREKSI_ABSEN: 'KOREKSI_ABSEN',
  },

  APPROVAL_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
  },

  DEFAULTS: {
    GEOFENCE_LAT: -6.613143,
    GEOFENCE_LNG: 106.684976,
    GEOFENCE_RADIUS_METERS: 50,
    WORK_CHECKIN_START: '06:00',
    WORK_CHECKIN_END: '07:15',
    WORK_CHECKOUT_START: '15:30',
    FRIDAY_CHECKOUT_START: '11:00',
    SATURDAY_IS_HOLIDAY: true,
    SUNDAY_IS_HOLIDAY: true,
    AUTO_ALFA_TIME: '16:30',
  },
} as const;
